# Generated by Django 3.1.2 on 2021-01-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizzes_background_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='background_text',
        ),
        migrations.AddField(
            model_name='question',
            name='background_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Contexto'),
        ),
    ]
