# Generated by Django 3.1.2 on 2021-01-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210117_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='background_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
