# Generated by Django 3.1.2 on 2021-01-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210117_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='background_text',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='background_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
