# Generated by Django 3.1.2 on 2021-01-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210117_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='background_text',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
